### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Sudn1** [Laysinity/TapSwap-Farming-bot#4]
Unknown error while getting Access Token: list index out of range | Response text: {"chq":"fbe8f3fee9f4f2f3bdffb5feb1f9b4e6ebfcefbdf8a0fcb5b4a6eff8e9e8eff3bdffa0fbe8f3fee9f4f2f3b5fbb1fab4e6fba

**Comment by Laysinity** [comment]
Пофиксил, обнови файл bot/utils/scripts.py

**Comment by Sudn1** [comment]
Спасибо
